@URL=http://localhost:3000

### Check if the server is running
GET {{URL}}

### Check if the API is live
GET {{URL}}/livez

### Shorten a url
POST {{URL}}/shorten
Content-Type: application/json

{
    "url": "https://www.mongodb.com/docs/manual/reference/method/db.collection.insertOne/#mongodb-method-db.collection.insertOne"
}


### Redirect to Original url
GET {{URL}}/6579fbbd652bb864b4623463